### ISSUE TITLE
Stops scanning avis after some time.

### ISSUE THREAD

**Issue by LargestBoi** [CodeAngel3/RipperStoreCredits#1]
After hopping a few worlds new avis fail to be scanned, tested by me going to a private world and it didn't even scan my avi

**Comment by CodeAngel3** [comment]
Hello, can you please tell me which version you are using?

**Comment by LoudestBoi** [comment]
6 stable

**Comment by LoudestBoi** [comment]
whoops closed it

**Comment by LoudestBoi** [comment]
Ah it doesn't stop scanning! It just stops displaying the fact that it scanned an avi and it already existed, it still rips new avis just doesn't tell u when an avi is already ripped!

**Comment by LoudestBoi** [comment]
Is this still a bug?

**Comment by CodeAngel3** [comment]
@LoudestBoi i tried to reproduce the bug a few times now without any success, maybe you have other Mods installed which cause this?

**Comment by LoudestBoi** [comment]
Nah it's the only mod I use, it stops showing avatars that already exist in console after like 6-7 world hops however it's fully functional when displaying a new AVI being sent off to the API for verification
